# Generated by Django 3.2.8 on 2025-02-03 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دانشکده')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره دانشجویی')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('user_level', models.CharField(choices=[('student', 'دانشجو'), ('admin', 'ادمین')], default='student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام استاد')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی استاد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('course_name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='تعداد واحد')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='ظرفیت کل')),
                ('class_day', models.CharField(max_length=50, verbose_name='روز کلاس (مثلاً Sat, Mon...)')),
                ('class_time', models.CharField(max_length=50, verbose_name='ساعت کلاس (مثلاً 10:00-12:00)')),
                ('exam_day', models.CharField(blank=True, max_length=50, verbose_name='روز امتحان')),
                ('exam_time', models.CharField(blank=True, max_length=50, verbose_name='ساعت امتحان')),
                ('corequisites', models.ManyToManyField(blank=True, related_name='is_corequisite_for', to='course_app.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_app.department')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.instructor')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='is_prerequisite_for', to='course_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
